-- Auto-generated swim_events seed (134 events)
INSERT INTO "swim_events" ("event_key", "label", "distance", "stroke", "course", "gender", "event_type", "relay_legs")
VALUES
('50_free_scy_m', '50 Freestyle', 50, 'free', 'SCY', 'male', 'individual', NULL),
('50_free_scy_f', '50 Freestyle', 50, 'free', 'SCY', 'female', 'individual', NULL),
('100_free_scy_m', '100 Freestyle', 100, 'free', 'SCY', 'male', 'individual', NULL),
('100_free_scy_f', '100 Freestyle', 100, 'free', 'SCY', 'female', 'individual', NULL),
('200_free_scy_m', '200 Freestyle', 200, 'free', 'SCY', 'male', 'individual', NULL),
('200_free_scy_f', '200 Freestyle', 200, 'free', 'SCY', 'female', 'individual', NULL),
('500_free_scy_m', '500 Freestyle', 500, 'free', 'SCY', 'male', 'individual', NULL),
('500_free_scy_f', '500 Freestyle', 500, 'free', 'SCY', 'female', 'individual', NULL),
('1000_free_scy_m', '1000 Freestyle', 1000, 'free', 'SCY', 'male', 'individual', NULL),
('1000_free_scy_f', '1000 Freestyle', 1000, 'free', 'SCY', 'female', 'individual', NULL),
('1650_free_scy_m', '1650 Freestyle', 1650, 'free', 'SCY', 'male', 'individual', NULL),
('1650_free_scy_f', '1650 Freestyle', 1650, 'free', 'SCY', 'female', 'individual', NULL),
('50_back_scy_m', '50 Backstroke', 50, 'back', 'SCY', 'male', 'individual', NULL),
('50_back_scy_f', '50 Backstroke', 50, 'back', 'SCY', 'female', 'individual', NULL),
('100_back_scy_m', '100 Backstroke', 100, 'back', 'SCY', 'male', 'individual', NULL),
('100_back_scy_f', '100 Backstroke', 100, 'back', 'SCY', 'female', 'individual', NULL),
('200_back_scy_m', '200 Backstroke', 200, 'back', 'SCY', 'male', 'individual', NULL),
('200_back_scy_f', '200 Backstroke', 200, 'back', 'SCY', 'female', 'individual', NULL),
('50_breast_scy_m', '50 Breaststroke', 50, 'breast', 'SCY', 'male', 'individual', NULL),
('50_breast_scy_f', '50 Breaststroke', 50, 'breast', 'SCY', 'female', 'individual', NULL),
('100_breast_scy_m', '100 Breaststroke', 100, 'breast', 'SCY', 'male', 'individual', NULL),
('100_breast_scy_f', '100 Breaststroke', 100, 'breast', 'SCY', 'female', 'individual', NULL),
('200_breast_scy_m', '200 Breaststroke', 200, 'breast', 'SCY', 'male', 'individual', NULL),
('200_breast_scy_f', '200 Breaststroke', 200, 'breast', 'SCY', 'female', 'individual', NULL),
('50_fly_scy_m', '50 Butterfly', 50, 'fly', 'SCY', 'male', 'individual', NULL),
('50_fly_scy_f', '50 Butterfly', 50, 'fly', 'SCY', 'female', 'individual', NULL),
('100_fly_scy_m', '100 Butterfly', 100, 'fly', 'SCY', 'male', 'individual', NULL),
('100_fly_scy_f', '100 Butterfly', 100, 'fly', 'SCY', 'female', 'individual', NULL),
('200_fly_scy_m', '200 Butterfly', 200, 'fly', 'SCY', 'male', 'individual', NULL),
('200_fly_scy_f', '200 Butterfly', 200, 'fly', 'SCY', 'female', 'individual', NULL),
('100_im_scy_m', '100 IM', 100, 'im', 'SCY', 'male', 'individual', NULL),
('100_im_scy_f', '100 IM', 100, 'im', 'SCY', 'female', 'individual', NULL),
('200_im_scy_m', '200 IM', 200, 'im', 'SCY', 'male', 'individual', NULL),
('200_im_scy_f', '200 IM', 200, 'im', 'SCY', 'female', 'individual', NULL),
('400_im_scy_m', '400 IM', 400, 'im', 'SCY', 'male', 'individual', NULL),
('400_im_scy_f', '400 IM', 400, 'im', 'SCY', 'female', 'individual', NULL),
('50_free_scm_m', '50 Freestyle', 50, 'free', 'SCM', 'male', 'individual', NULL),
('50_free_scm_f', '50 Freestyle', 50, 'free', 'SCM', 'female', 'individual', NULL),
('100_free_scm_m', '100 Freestyle', 100, 'free', 'SCM', 'male', 'individual', NULL),
('100_free_scm_f', '100 Freestyle', 100, 'free', 'SCM', 'female', 'individual', NULL),
('200_free_scm_m', '200 Freestyle', 200, 'free', 'SCM', 'male', 'individual', NULL),
('200_free_scm_f', '200 Freestyle', 200, 'free', 'SCM', 'female', 'individual', NULL),
('400_free_scm_m', '400 Freestyle', 400, 'free', 'SCM', 'male', 'individual', NULL),
('400_free_scm_f', '400 Freestyle', 400, 'free', 'SCM', 'female', 'individual', NULL),
('800_free_scm_m', '800 Freestyle', 800, 'free', 'SCM', 'male', 'individual', NULL),
('800_free_scm_f', '800 Freestyle', 800, 'free', 'SCM', 'female', 'individual', NULL),
('1500_free_scm_m', '1500 Freestyle', 1500, 'free', 'SCM', 'male', 'individual', NULL),
('1500_free_scm_f', '1500 Freestyle', 1500, 'free', 'SCM', 'female', 'individual', NULL),
('50_back_scm_m', '50 Backstroke', 50, 'back', 'SCM', 'male', 'individual', NULL),
('50_back_scm_f', '50 Backstroke', 50, 'back', 'SCM', 'female', 'individual', NULL),
('100_back_scm_m', '100 Backstroke', 100, 'back', 'SCM', 'male', 'individual', NULL),
('100_back_scm_f', '100 Backstroke', 100, 'back', 'SCM', 'female', 'individual', NULL),
('200_back_scm_m', '200 Backstroke', 200, 'back', 'SCM', 'male', 'individual', NULL),
('200_back_scm_f', '200 Backstroke', 200, 'back', 'SCM', 'female', 'individual', NULL),
('50_breast_scm_m', '50 Breaststroke', 50, 'breast', 'SCM', 'male', 'individual', NULL),
('50_breast_scm_f', '50 Breaststroke', 50, 'breast', 'SCM', 'female', 'individual', NULL),
('100_breast_scm_m', '100 Breaststroke', 100, 'breast', 'SCM', 'male', 'individual', NULL),
('100_breast_scm_f', '100 Breaststroke', 100, 'breast', 'SCM', 'female', 'individual', NULL),
('200_breast_scm_m', '200 Breaststroke', 200, 'breast', 'SCM', 'male', 'individual', NULL),
('200_breast_scm_f', '200 Breaststroke', 200, 'breast', 'SCM', 'female', 'individual', NULL),
('50_fly_scm_m', '50 Butterfly', 50, 'fly', 'SCM', 'male', 'individual', NULL),
('50_fly_scm_f', '50 Butterfly', 50, 'fly', 'SCM', 'female', 'individual', NULL),
('100_fly_scm_m', '100 Butterfly', 100, 'fly', 'SCM', 'male', 'individual', NULL),
('100_fly_scm_f', '100 Butterfly', 100, 'fly', 'SCM', 'female', 'individual', NULL),
('200_fly_scm_m', '200 Butterfly', 200, 'fly', 'SCM', 'male', 'individual', NULL),
('200_fly_scm_f', '200 Butterfly', 200, 'fly', 'SCM', 'female', 'individual', NULL),
('100_im_scm_m', '100 IM', 100, 'im', 'SCM', 'male', 'individual', NULL),
('100_im_scm_f', '100 IM', 100, 'im', 'SCM', 'female', 'individual', NULL),
('200_im_scm_m', '200 IM', 200, 'im', 'SCM', 'male', 'individual', NULL),
('200_im_scm_f', '200 IM', 200, 'im', 'SCM', 'female', 'individual', NULL),
('400_im_scm_m', '400 IM', 400, 'im', 'SCM', 'male', 'individual', NULL),
('400_im_scm_f', '400 IM', 400, 'im', 'SCM', 'female', 'individual', NULL),
('50_free_lcm_m', '50 Freestyle', 50, 'free', 'LCM', 'male', 'individual', NULL),
('50_free_lcm_f', '50 Freestyle', 50, 'free', 'LCM', 'female', 'individual', NULL),
('100_free_lcm_m', '100 Freestyle', 100, 'free', 'LCM', 'male', 'individual', NULL),
('100_free_lcm_f', '100 Freestyle', 100, 'free', 'LCM', 'female', 'individual', NULL),
('200_free_lcm_m', '200 Freestyle', 200, 'free', 'LCM', 'male', 'individual', NULL),
('200_free_lcm_f', '200 Freestyle', 200, 'free', 'LCM', 'female', 'individual', NULL),
('400_free_lcm_m', '400 Freestyle', 400, 'free', 'LCM', 'male', 'individual', NULL),
('400_free_lcm_f', '400 Freestyle', 400, 'free', 'LCM', 'female', 'individual', NULL),
('800_free_lcm_m', '800 Freestyle', 800, 'free', 'LCM', 'male', 'individual', NULL),
('800_free_lcm_f', '800 Freestyle', 800, 'free', 'LCM', 'female', 'individual', NULL),
('1500_free_lcm_m', '1500 Freestyle', 1500, 'free', 'LCM', 'male', 'individual', NULL),
('1500_free_lcm_f', '1500 Freestyle', 1500, 'free', 'LCM', 'female', 'individual', NULL),
('50_back_lcm_m', '50 Backstroke', 50, 'back', 'LCM', 'male', 'individual', NULL),
('50_back_lcm_f', '50 Backstroke', 50, 'back', 'LCM', 'female', 'individual', NULL),
('100_back_lcm_m', '100 Backstroke', 100, 'back', 'LCM', 'male', 'individual', NULL),
('100_back_lcm_f', '100 Backstroke', 100, 'back', 'LCM', 'female', 'individual', NULL),
('200_back_lcm_m', '200 Backstroke', 200, 'back', 'LCM', 'male', 'individual', NULL),
('200_back_lcm_f', '200 Backstroke', 200, 'back', 'LCM', 'female', 'individual', NULL),
('50_breast_lcm_m', '50 Breaststroke', 50, 'breast', 'LCM', 'male', 'individual', NULL),
('50_breast_lcm_f', '50 Breaststroke', 50, 'breast', 'LCM', 'female', 'individual', NULL),
('100_breast_lcm_m', '100 Breaststroke', 100, 'breast', 'LCM', 'male', 'individual', NULL),
('100_breast_lcm_f', '100 Breaststroke', 100, 'breast', 'LCM', 'female', 'individual', NULL),
('200_breast_lcm_m', '200 Breaststroke', 200, 'breast', 'LCM', 'male', 'individual', NULL),
('200_breast_lcm_f', '200 Breaststroke', 200, 'breast', 'LCM', 'female', 'individual', NULL),
('50_fly_lcm_m', '50 Butterfly', 50, 'fly', 'LCM', 'male', 'individual', NULL),
('50_fly_lcm_f', '50 Butterfly', 50, 'fly', 'LCM', 'female', 'individual', NULL),
('100_fly_lcm_m', '100 Butterfly', 100, 'fly', 'LCM', 'male', 'individual', NULL),
('100_fly_lcm_f', '100 Butterfly', 100, 'fly', 'LCM', 'female', 'individual', NULL),
('200_fly_lcm_m', '200 Butterfly', 200, 'fly', 'LCM', 'male', 'individual', NULL),
('200_fly_lcm_f', '200 Butterfly', 200, 'fly', 'LCM', 'female', 'individual', NULL),
('200_im_lcm_m', '200 IM', 200, 'im', 'LCM', 'male', 'individual', NULL),
('200_im_lcm_f', '200 IM', 200, 'im', 'LCM', 'female', 'individual', NULL),
('400_im_lcm_m', '400 IM', 400, 'im', 'LCM', 'male', 'individual', NULL),
('400_im_lcm_f', '400 IM', 400, 'im', 'LCM', 'female', 'individual', NULL),
('200_free_relay_scy_m', '200 Freestyle Relay', 200, 'free_relay', 'SCY', 'male', 'relay', 4),
('200_free_relay_scy_f', '200 Freestyle Relay', 200, 'free_relay', 'SCY', 'female', 'relay', 4),
('200_free_relay_scm_m', '200 Freestyle Relay', 200, 'free_relay', 'SCM', 'male', 'relay', 4),
('200_free_relay_scm_f', '200 Freestyle Relay', 200, 'free_relay', 'SCM', 'female', 'relay', 4),
('200_free_relay_lcm_m', '200 Freestyle Relay', 200, 'free_relay', 'LCM', 'male', 'relay', 4),
('200_free_relay_lcm_f', '200 Freestyle Relay', 200, 'free_relay', 'LCM', 'female', 'relay', 4),
('400_free_relay_scy_m', '400 Freestyle Relay', 400, 'free_relay', 'SCY', 'male', 'relay', 4),
('400_free_relay_scy_f', '400 Freestyle Relay', 400, 'free_relay', 'SCY', 'female', 'relay', 4),
('400_free_relay_scm_m', '400 Freestyle Relay', 400, 'free_relay', 'SCM', 'male', 'relay', 4),
('400_free_relay_scm_f', '400 Freestyle Relay', 400, 'free_relay', 'SCM', 'female', 'relay', 4),
('400_free_relay_lcm_m', '400 Freestyle Relay', 400, 'free_relay', 'LCM', 'male', 'relay', 4),
('400_free_relay_lcm_f', '400 Freestyle Relay', 400, 'free_relay', 'LCM', 'female', 'relay', 4),
('800_free_relay_scm_m', '800 Freestyle Relay', 800, 'free_relay', 'SCM', 'male', 'relay', 4),
('800_free_relay_scm_f', '800 Freestyle Relay', 800, 'free_relay', 'SCM', 'female', 'relay', 4),
('800_free_relay_lcm_m', '800 Freestyle Relay', 800, 'free_relay', 'LCM', 'male', 'relay', 4),
('800_free_relay_lcm_f', '800 Freestyle Relay', 800, 'free_relay', 'LCM', 'female', 'relay', 4),
('200_medley_relay_scy_m', '200 Medley Relay', 200, 'medley_relay', 'SCY', 'male', 'relay', 4),
('200_medley_relay_scy_f', '200 Medley Relay', 200, 'medley_relay', 'SCY', 'female', 'relay', 4),
('200_medley_relay_scm_m', '200 Medley Relay', 200, 'medley_relay', 'SCM', 'male', 'relay', 4),
('200_medley_relay_scm_f', '200 Medley Relay', 200, 'medley_relay', 'SCM', 'female', 'relay', 4),
('200_medley_relay_lcm_m', '200 Medley Relay', 200, 'medley_relay', 'LCM', 'male', 'relay', 4),
('200_medley_relay_lcm_f', '200 Medley Relay', 200, 'medley_relay', 'LCM', 'female', 'relay', 4),
('400_medley_relay_scy_m', '400 Medley Relay', 400, 'medley_relay', 'SCY', 'male', 'relay', 4),
('400_medley_relay_scy_f', '400 Medley Relay', 400, 'medley_relay', 'SCY', 'female', 'relay', 4),
('400_medley_relay_scm_m', '400 Medley Relay', 400, 'medley_relay', 'SCM', 'male', 'relay', 4),
('400_medley_relay_scm_f', '400 Medley Relay', 400, 'medley_relay', 'SCM', 'female', 'relay', 4),
('400_medley_relay_lcm_m', '400 Medley Relay', 400, 'medley_relay', 'LCM', 'male', 'relay', 4),
('400_medley_relay_lcm_f', '400 Medley Relay', 400, 'medley_relay', 'LCM', 'female', 'relay', 4)
ON CONFLICT ("event_key") DO NOTHING;
