-- Auto-generated swim_events seed (134 events)
INSERT INTO "swim_events" ("event_key", "label", "distance", "stroke", "course", "gender", "event_type", "relay_legs")
VALUES
('50_free_scy_m', '50 Freestyle SCY', 50, 'free', 'SCY', 'm', 'individual', NULL),
('50_free_scy_f', '50 Freestyle SCY', 50, 'free', 'SCY', 'f', 'individual', NULL),
('100_free_scy_m', '100 Freestyle SCY', 100, 'free', 'SCY', 'm', 'individual', NULL),
('100_free_scy_f', '100 Freestyle SCY', 100, 'free', 'SCY', 'f', 'individual', NULL),
('200_free_scy_m', '200 Freestyle SCY', 200, 'free', 'SCY', 'm', 'individual', NULL),
('200_free_scy_f', '200 Freestyle SCY', 200, 'free', 'SCY', 'f', 'individual', NULL),
('500_free_scy_m', '500 Freestyle SCY', 500, 'free', 'SCY', 'm', 'individual', NULL),
('500_free_scy_f', '500 Freestyle SCY', 500, 'free', 'SCY', 'f', 'individual', NULL),
('1000_free_scy_m', '1000 Freestyle SCY', 1000, 'free', 'SCY', 'm', 'individual', NULL),
('1000_free_scy_f', '1000 Freestyle SCY', 1000, 'free', 'SCY', 'f', 'individual', NULL),
('1650_free_scy_m', '1650 Freestyle SCY', 1650, 'free', 'SCY', 'm', 'individual', NULL),
('1650_free_scy_f', '1650 Freestyle SCY', 1650, 'free', 'SCY', 'f', 'individual', NULL),
('50_back_scy_m', '50 Backstroke SCY', 50, 'back', 'SCY', 'm', 'individual', NULL),
('50_back_scy_f', '50 Backstroke SCY', 50, 'back', 'SCY', 'f', 'individual', NULL),
('100_back_scy_m', '100 Backstroke SCY', 100, 'back', 'SCY', 'm', 'individual', NULL),
('100_back_scy_f', '100 Backstroke SCY', 100, 'back', 'SCY', 'f', 'individual', NULL),
('200_back_scy_m', '200 Backstroke SCY', 200, 'back', 'SCY', 'm', 'individual', NULL),
('200_back_scy_f', '200 Backstroke SCY', 200, 'back', 'SCY', 'f', 'individual', NULL),
('50_breast_scy_m', '50 Breaststroke SCY', 50, 'breast', 'SCY', 'm', 'individual', NULL),
('50_breast_scy_f', '50 Breaststroke SCY', 50, 'breast', 'SCY', 'f', 'individual', NULL),
('100_breast_scy_m', '100 Breaststroke SCY', 100, 'breast', 'SCY', 'm', 'individual', NULL),
('100_breast_scy_f', '100 Breaststroke SCY', 100, 'breast', 'SCY', 'f', 'individual', NULL),
('200_breast_scy_m', '200 Breaststroke SCY', 200, 'breast', 'SCY', 'm', 'individual', NULL),
('200_breast_scy_f', '200 Breaststroke SCY', 200, 'breast', 'SCY', 'f', 'individual', NULL),
('50_fly_scy_m', '50 Butterfly SCY', 50, 'fly', 'SCY', 'm', 'individual', NULL),
('50_fly_scy_f', '50 Butterfly SCY', 50, 'fly', 'SCY', 'f', 'individual', NULL),
('100_fly_scy_m', '100 Butterfly SCY', 100, 'fly', 'SCY', 'm', 'individual', NULL),
('100_fly_scy_f', '100 Butterfly SCY', 100, 'fly', 'SCY', 'f', 'individual', NULL),
('200_fly_scy_m', '200 Butterfly SCY', 200, 'fly', 'SCY', 'm', 'individual', NULL),
('200_fly_scy_f', '200 Butterfly SCY', 200, 'fly', 'SCY', 'f', 'individual', NULL),
('100_im_scy_m', '100 Individual Medley SCY', 100, 'im', 'SCY', 'm', 'individual', NULL),
('100_im_scy_f', '100 Individual Medley SCY', 100, 'im', 'SCY', 'f', 'individual', NULL),
('200_im_scy_m', '200 Individual Medley SCY', 200, 'im', 'SCY', 'm', 'individual', NULL),
('200_im_scy_f', '200 Individual Medley SCY', 200, 'im', 'SCY', 'f', 'individual', NULL),
('400_im_scy_m', '400 Individual Medley SCY', 400, 'im', 'SCY', 'm', 'individual', NULL),
('400_im_scy_f', '400 Individual Medley SCY', 400, 'im', 'SCY', 'f', 'individual', NULL),
('50_free_scm_m', '50 Freestyle SCM', 50, 'free', 'SCM', 'm', 'individual', NULL),
('50_free_scm_f', '50 Freestyle SCM', 50, 'free', 'SCM', 'f', 'individual', NULL),
('100_free_scm_m', '100 Freestyle SCM', 100, 'free', 'SCM', 'm', 'individual', NULL),
('100_free_scm_f', '100 Freestyle SCM', 100, 'free', 'SCM', 'f', 'individual', NULL),
('200_free_scm_m', '200 Freestyle SCM', 200, 'free', 'SCM', 'm', 'individual', NULL),
('200_free_scm_f', '200 Freestyle SCM', 200, 'free', 'SCM', 'f', 'individual', NULL),
('400_free_scm_m', '400 Freestyle SCM', 400, 'free', 'SCM', 'm', 'individual', NULL),
('400_free_scm_f', '400 Freestyle SCM', 400, 'free', 'SCM', 'f', 'individual', NULL),
('800_free_scm_m', '800 Freestyle SCM', 800, 'free', 'SCM', 'm', 'individual', NULL),
('800_free_scm_f', '800 Freestyle SCM', 800, 'free', 'SCM', 'f', 'individual', NULL),
('1500_free_scm_m', '1500 Freestyle SCM', 1500, 'free', 'SCM', 'm', 'individual', NULL),
('1500_free_scm_f', '1500 Freestyle SCM', 1500, 'free', 'SCM', 'f', 'individual', NULL),
('50_back_scm_m', '50 Backstroke SCM', 50, 'back', 'SCM', 'm', 'individual', NULL),
('50_back_scm_f', '50 Backstroke SCM', 50, 'back', 'SCM', 'f', 'individual', NULL),
('100_back_scm_m', '100 Backstroke SCM', 100, 'back', 'SCM', 'm', 'individual', NULL),
('100_back_scm_f', '100 Backstroke SCM', 100, 'back', 'SCM', 'f', 'individual', NULL),
('200_back_scm_m', '200 Backstroke SCM', 200, 'back', 'SCM', 'm', 'individual', NULL),
('200_back_scm_f', '200 Backstroke SCM', 200, 'back', 'SCM', 'f', 'individual', NULL),
('50_breast_scm_m', '50 Breaststroke SCM', 50, 'breast', 'SCM', 'm', 'individual', NULL),
('50_breast_scm_f', '50 Breaststroke SCM', 50, 'breast', 'SCM', 'f', 'individual', NULL),
('100_breast_scm_m', '100 Breaststroke SCM', 100, 'breast', 'SCM', 'm', 'individual', NULL),
('100_breast_scm_f', '100 Breaststroke SCM', 100, 'breast', 'SCM', 'f', 'individual', NULL),
('200_breast_scm_m', '200 Breaststroke SCM', 200, 'breast', 'SCM', 'm', 'individual', NULL),
('200_breast_scm_f', '200 Breaststroke SCM', 200, 'breast', 'SCM', 'f', 'individual', NULL),
('50_fly_scm_m', '50 Butterfly SCM', 50, 'fly', 'SCM', 'm', 'individual', NULL),
('50_fly_scm_f', '50 Butterfly SCM', 50, 'fly', 'SCM', 'f', 'individual', NULL),
('100_fly_scm_m', '100 Butterfly SCM', 100, 'fly', 'SCM', 'm', 'individual', NULL),
('100_fly_scm_f', '100 Butterfly SCM', 100, 'fly', 'SCM', 'f', 'individual', NULL),
('200_fly_scm_m', '200 Butterfly SCM', 200, 'fly', 'SCM', 'm', 'individual', NULL),
('200_fly_scm_f', '200 Butterfly SCM', 200, 'fly', 'SCM', 'f', 'individual', NULL),
('100_im_scm_m', '100 Individual Medley SCM', 100, 'im', 'SCM', 'm', 'individual', NULL),
('100_im_scm_f', '100 Individual Medley SCM', 100, 'im', 'SCM', 'f', 'individual', NULL),
('200_im_scm_m', '200 Individual Medley SCM', 200, 'im', 'SCM', 'm', 'individual', NULL),
('200_im_scm_f', '200 Individual Medley SCM', 200, 'im', 'SCM', 'f', 'individual', NULL),
('400_im_scm_m', '400 Individual Medley SCM', 400, 'im', 'SCM', 'm', 'individual', NULL),
('400_im_scm_f', '400 Individual Medley SCM', 400, 'im', 'SCM', 'f', 'individual', NULL),
('50_free_lcm_m', '50 Freestyle LCM', 50, 'free', 'LCM', 'm', 'individual', NULL),
('50_free_lcm_f', '50 Freestyle LCM', 50, 'free', 'LCM', 'f', 'individual', NULL),
('100_free_lcm_m', '100 Freestyle LCM', 100, 'free', 'LCM', 'm', 'individual', NULL),
('100_free_lcm_f', '100 Freestyle LCM', 100, 'free', 'LCM', 'f', 'individual', NULL),
('200_free_lcm_m', '200 Freestyle LCM', 200, 'free', 'LCM', 'm', 'individual', NULL),
('200_free_lcm_f', '200 Freestyle LCM', 200, 'free', 'LCM', 'f', 'individual', NULL),
('400_free_lcm_m', '400 Freestyle LCM', 400, 'free', 'LCM', 'm', 'individual', NULL),
('400_free_lcm_f', '400 Freestyle LCM', 400, 'free', 'LCM', 'f', 'individual', NULL),
('800_free_lcm_m', '800 Freestyle LCM', 800, 'free', 'LCM', 'm', 'individual', NULL),
('800_free_lcm_f', '800 Freestyle LCM', 800, 'free', 'LCM', 'f', 'individual', NULL),
('1500_free_lcm_m', '1500 Freestyle LCM', 1500, 'free', 'LCM', 'm', 'individual', NULL),
('1500_free_lcm_f', '1500 Freestyle LCM', 1500, 'free', 'LCM', 'f', 'individual', NULL),
('50_back_lcm_m', '50 Backstroke LCM', 50, 'back', 'LCM', 'm', 'individual', NULL),
('50_back_lcm_f', '50 Backstroke LCM', 50, 'back', 'LCM', 'f', 'individual', NULL),
('100_back_lcm_m', '100 Backstroke LCM', 100, 'back', 'LCM', 'm', 'individual', NULL),
('100_back_lcm_f', '100 Backstroke LCM', 100, 'back', 'LCM', 'f', 'individual', NULL),
('200_back_lcm_m', '200 Backstroke LCM', 200, 'back', 'LCM', 'm', 'individual', NULL),
('200_back_lcm_f', '200 Backstroke LCM', 200, 'back', 'LCM', 'f', 'individual', NULL),
('50_breast_lcm_m', '50 Breaststroke LCM', 50, 'breast', 'LCM', 'm', 'individual', NULL),
('50_breast_lcm_f', '50 Breaststroke LCM', 50, 'breast', 'LCM', 'f', 'individual', NULL),
('100_breast_lcm_m', '100 Breaststroke LCM', 100, 'breast', 'LCM', 'm', 'individual', NULL),
('100_breast_lcm_f', '100 Breaststroke LCM', 100, 'breast', 'LCM', 'f', 'individual', NULL),
('200_breast_lcm_m', '200 Breaststroke LCM', 200, 'breast', 'LCM', 'm', 'individual', NULL),
('200_breast_lcm_f', '200 Breaststroke LCM', 200, 'breast', 'LCM', 'f', 'individual', NULL),
('50_fly_lcm_m', '50 Butterfly LCM', 50, 'fly', 'LCM', 'm', 'individual', NULL),
('50_fly_lcm_f', '50 Butterfly LCM', 50, 'fly', 'LCM', 'f', 'individual', NULL),
('100_fly_lcm_m', '100 Butterfly LCM', 100, 'fly', 'LCM', 'm', 'individual', NULL),
('100_fly_lcm_f', '100 Butterfly LCM', 100, 'fly', 'LCM', 'f', 'individual', NULL),
('200_fly_lcm_m', '200 Butterfly LCM', 200, 'fly', 'LCM', 'm', 'individual', NULL),
('200_fly_lcm_f', '200 Butterfly LCM', 200, 'fly', 'LCM', 'f', 'individual', NULL),
('200_im_lcm_m', '200 Individual Medley LCM', 200, 'im', 'LCM', 'm', 'individual', NULL),
('200_im_lcm_f', '200 Individual Medley LCM', 200, 'im', 'LCM', 'f', 'individual', NULL),
('400_im_lcm_m', '400 Individual Medley LCM', 400, 'im', 'LCM', 'm', 'individual', NULL),
('400_im_lcm_f', '400 Individual Medley LCM', 400, 'im', 'LCM', 'f', 'individual', NULL),
('200_free_relay_scy_m', '200 Freestyle Relay SCY', 200, 'free_relay', 'SCY', 'm', 'relay', 4),
('200_free_relay_scy_f', '200 Freestyle Relay SCY', 200, 'free_relay', 'SCY', 'f', 'relay', 4),
('200_free_relay_scm_m', '200 Freestyle Relay SCM', 200, 'free_relay', 'SCM', 'm', 'relay', 4),
('200_free_relay_scm_f', '200 Freestyle Relay SCM', 200, 'free_relay', 'SCM', 'f', 'relay', 4),
('200_free_relay_lcm_m', '200 Freestyle Relay LCM', 200, 'free_relay', 'LCM', 'm', 'relay', 4),
('200_free_relay_lcm_f', '200 Freestyle Relay LCM', 200, 'free_relay', 'LCM', 'f', 'relay', 4),
('400_free_relay_scy_m', '400 Freestyle Relay SCY', 400, 'free_relay', 'SCY', 'm', 'relay', 4),
('400_free_relay_scy_f', '400 Freestyle Relay SCY', 400, 'free_relay', 'SCY', 'f', 'relay', 4),
('400_free_relay_scm_m', '400 Freestyle Relay SCM', 400, 'free_relay', 'SCM', 'm', 'relay', 4),
('400_free_relay_scm_f', '400 Freestyle Relay SCM', 400, 'free_relay', 'SCM', 'f', 'relay', 4),
('400_free_relay_lcm_m', '400 Freestyle Relay LCM', 400, 'free_relay', 'LCM', 'm', 'relay', 4),
('400_free_relay_lcm_f', '400 Freestyle Relay LCM', 400, 'free_relay', 'LCM', 'f', 'relay', 4),
('800_free_relay_scm_m', '800 Freestyle Relay SCM', 800, 'free_relay', 'SCM', 'm', 'relay', 4),
('800_free_relay_scm_f', '800 Freestyle Relay SCM', 800, 'free_relay', 'SCM', 'f', 'relay', 4),
('800_free_relay_lcm_m', '800 Freestyle Relay LCM', 800, 'free_relay', 'LCM', 'm', 'relay', 4),
('800_free_relay_lcm_f', '800 Freestyle Relay LCM', 800, 'free_relay', 'LCM', 'f', 'relay', 4),
('200_medley_relay_scy_m', '200 Medley Relay SCY', 200, 'medley_relay', 'SCY', 'm', 'relay', 4),
('200_medley_relay_scy_f', '200 Medley Relay SCY', 200, 'medley_relay', 'SCY', 'f', 'relay', 4),
('200_medley_relay_scm_m', '200 Medley Relay SCM', 200, 'medley_relay', 'SCM', 'm', 'relay', 4),
('200_medley_relay_scm_f', '200 Medley Relay SCM', 200, 'medley_relay', 'SCM', 'f', 'relay', 4),
('200_medley_relay_lcm_m', '200 Medley Relay LCM', 200, 'medley_relay', 'LCM', 'm', 'relay', 4),
('200_medley_relay_lcm_f', '200 Medley Relay LCM', 200, 'medley_relay', 'LCM', 'f', 'relay', 4),
('400_medley_relay_scy_m', '400 Medley Relay SCY', 400, 'medley_relay', 'SCY', 'm', 'relay', 4),
('400_medley_relay_scy_f', '400 Medley Relay SCY', 400, 'medley_relay', 'SCY', 'f', 'relay', 4),
('400_medley_relay_scm_m', '400 Medley Relay SCM', 400, 'medley_relay', 'SCM', 'm', 'relay', 4),
('400_medley_relay_scm_f', '400 Medley Relay SCM', 400, 'medley_relay', 'SCM', 'f', 'relay', 4),
('400_medley_relay_lcm_m', '400 Medley Relay LCM', 400, 'medley_relay', 'LCM', 'm', 'relay', 4),
('400_medley_relay_lcm_f', '400 Medley Relay LCM', 400, 'medley_relay', 'LCM', 'f', 'relay', 4)
ON CONFLICT ("event_key") DO NOTHING;
