name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "24"
      - uses: pnpm/action-setup@v6
      - name: Install dependencies
        run: pnpm install
      - name: Run linter
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "24"
      - uses: pnpm/action-setup@v6
      - name: Install dependencies
        run: pnpm install
      - name: Run unit tests with coverage
        run: pnpm test
